In [1]:
#Numpy uses C to processes arrays and matrices faster than python
import numpy as np

# Array Generation

In [12]:
#We can make a numpy array by feeding in a list of rows
my_array=np.array([[0,1,2,3],[4,5,6,7]])
my_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
#We can also make an array using Numpy's equivalent of range
my_array=np.arange(0,4,1)
my_array

array([0, 1, 2, 3])

In [113]:
#Alternatively, we can divide the range into N chunks using np.linspace
#Here, the endpoint is included by default
my_array=np.linspace(0,4,2,endpoint=False)
my_array

array([ 0.,  2.])

In [114]:
#To create an array of zeros use np.zeros(shape) (can also do "np.ones")
np.zeros((10,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [115]:
#To create a random array np.random methods
#These include:
#np.random.rand(shape) for random floats between 1 and 0
#np.random.normal(size=shape) for normal distribution between 1 and 0
#np.random.randint(low,high,size) for random ints between low and high
np.random.rand(2,3)

array([[ 0.4711587 ,  0.24974823,  0.90466567],
       [ 0.40750187,  0.54854633,  0.44890805]])

# Array information

In [116]:
#Getting data type of the array
my_array.dtype

dtype('float64')

In [19]:
#Getting shape of an array
my_array.shape

(2, 4)

In [20]:
#Getting number of array elements
my_array.size

8

In [21]:
#Getting number of dimensions of an array
my_array.ndim

2

# Editing an array

In [121]:
my_array=np.array([[0,1,2,3],[4,5,6,7]])
my_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [122]:
#We can change the datatype of the array
my_array.astype(str)

array([['0', '1', '2', '3'],
       ['4', '5', '6', '7']], 
      dtype='<U21')

In [127]:
#We can reshape the array
my_array.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

# Indexing Arrays

In [46]:
#You can index arrays using typical python slicing (rows, columns)
my_array[0][0:3]

array([0, 1, 2])

# Doing Math with arrays

In [22]:
#You can do math over the entire array
np.mean(my_array)

3.5

In [26]:
#Use axis=0 to do math within each column
np.mean(my_array,axis=0)

array([ 2.,  3.,  4.,  5.])

In [27]:
#use axis=1 to do math within each row
np.mean(my_array,axis=1)

array([ 1.5,  5.5])

In [101]:
#You can do element wise math with typical symbols
2 * np.array([[1,2,3],[2,4,6]])

array([[ 2,  4,  6],
       [ 4,  8, 12]])

In [102]:
np.array([[1,2,3],[2,4,6]]) * np.array([[1,2,3],[2,4,6]])

array([[ 1,  4,  9],
       [ 4, 16, 36]])

In [103]:
np.array([1,2,3])* np.array([[1,2,3],[2,4,6]])

array([[ 1,  4,  9],
       [ 2,  8, 18]])

In [105]:
#To do matrix multiplication, use np.dot(A,B)
np.dot(np.array([[1,2],[2,4]]),np.array([[1,2],[2,4]]))

array([[ 5, 10],
       [10, 20]])

In [132]:
#We can convolve two arrays, and specify full, valid, or same modes
arr1=np.array([3,5])  #gets flipped to [5,3]
arr2=np.array([1,2,3,4])
np.convolve(arr1,arr2,mode='valid')

array([11, 19, 27])

# Vectorizing Functions

In [140]:
#We can run a function over each element of an array using np.vectorize

#Function that caps values at some value "b"
def AtMost(a,b):
    if a > b:
        return b
    return a

AtMost_vect = np.vectorize(AtMost)
AtMost_vect([1,2,3,4,5,6],3)

array([1, 2, 3, 3, 3, 3])